run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - govet

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/mordenhost/whm2bunny

  misspell:
    locale: US

issues:
  exclude-dirs:
    - scripts

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
        - gocritic

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
