#!/bin/bash
# One-command installer for whm2bunny
# Usage: curl -sSL https://get.mordenhost.com/whm2bunny | bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run as root${NC}"
    echo "Please run: sudo $0"
    exit 1
fi

# Check if cPanel is installed
if [ ! -d /usr/local/cpanel ]; then
    echo -e "${RED}Error: cPanel installation not found${NC}"
    echo "This installer is designed for cPanel/WHM servers"
    exit 1
fi

echo -e "${GREEN}=== whm2bunny Installer ===${NC}"
echo ""

# Detect architecture
ARCH=$(uname -m)
case $ARCH in
    x86_64)
        ARCH="amd64"
        ;;
    aarch64|arm64)
        ARCH="arm64"
        ;;
    i386|i686)
        ARCH="386"
        ;;
    *)
        echo -e "${RED}Error: Unsupported architecture: $ARCH${NC}"
        exit 1
        ;;
esac

echo -e "Detected architecture: ${YELLOW}${ARCH}${NC}"

# Create directories
echo -e "${GREEN}Creating directories...${NC}"
mkdir -p /opt/whm2bunny
mkdir -p /var/log/whm2bunny
mkdir -p /var/lib/whm2bunny
mkdir -p /etc/whm2bunny

# Download or copy binary
BINARY_PATH="/opt/whm2bunny/whm2bunny"

# Check if there's a local binary in current directory
if [ -f "./whm2bunny" ] && [ -x "./whm2bunny" ]; then
    echo -e "${GREEN}Using local binary...${NC}"
    cp ./whm2bunny "$BINARY_PATH"
else
    # Download from releases
    RELEASE_URL="https://releases.mordenhost.com/whm2bunny/latest/whm2bunny-linux-${ARCH}"
    echo -e "${GREEN}Downloading binary from:${NC} $RELEASE_URL"

    if ! curl -fsSL "$RELEASE_URL" -o "$BINARY_PATH"; then
        echo -e "${RED}Error: Failed to download binary${NC}"
        echo "Please download manually or build from source"
        exit 1
    fi
fi

# Make binary executable
chmod +x "$BINARY_PATH"
echo -e "${GREEN}Binary installed to: $BINARY_PATH${NC}"

# Generate config if not exists
if [ ! -f /etc/whm2bunny/config.yaml ]; then
    echo -e "${GREEN}Generating default configuration...${NC}"
    "$BINARY_PATH" config generate /etc/whm2bunny/config.yaml
    echo -e "${YELLOW}Configuration generated: /etc/whm2bunny/config.yaml${NC}"
    echo -e "${YELLOW}Please edit this file to add your API keys${NC}"
else
    echo -e "${YELLOW}Configuration file already exists: /etc/whm2bunny/config.yaml${NC}"
fi

# Install Perl hook module
echo -e "${GREEN}Installing cPanel hook module...${NC}"
cp "$(dirname "$0")/hook_handler.pl" /usr/local/cpanel/Whm2bunnyHook.pm

# Check if WHM2BUNNY_SECRET is set
if [ -z "$WHM2BUNNY_SECRET" ]; then
    # Generate random secret
    WHM2BUNNY_SECRET=$(openssl rand -hex 32)
    echo -e "${YELLOW}Generated webhook secret: $WHM2BUNNY_SECRET${NC}"
fi

# Create environment file
cat > /etc/whm2bunny/env << EOF
# whm2bunny environment variables
# Generated by installer on $(date)

# Bunny.net API Configuration
BUNNY_API_KEY=\${BUNNY_API_KEY:-}

# Reverse Proxy Configuration
REVERSE_PROXY_IP=\${REVERSE_PROXY_IP:-}

# Webhook Secret (keep this secret!)
WHM_HOOK_SECRET=$WHM2BUNNY_SECRET

# Telegram Notifications (optional)
TELEGRAM_BOT_TOKEN=\${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_CHAT_ID=\${TELEGRAM_CHAT_ID:-}

# State file location
STATE_FILE=/var/lib/whm2bunny/state.json

# Debug mode (uncomment to enable)
# DEBUG=true
EOF

chmod 600 /etc/whm2bunny/env
echo -e "${GREEN}Environment file created: /etc/whm2bunny/env${NC}"

# Create systemd service
echo -e "${GREEN}Installing systemd service...${NC}"
cat > /etc/systemd/system/whm2bunny.service << 'EOSERVICE'
[Unit]
Description=whm2bunny - BunnyDNS/BunnyCDN Provisioner
Documentation=https://github.com/mordenhost/whm2bunny
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/opt/whm2bunny/whm2bunny serve --config /etc/whm2bunny/config.yaml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=whm2bunny

# Security settings
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/whm2bunny /var/log/whm2bunny /etc/whm2bunny
EnvironmentFile=/etc/whm2bunny/env

# Resource limits
LimitNOFILE=65536
LimitNPROC=4096

[Install]
WantedBy=multi-user.target
EOSERVICE

# Reload systemd and enable service
systemctl daemon-reload
systemctl enable whm2bunny

echo ""
echo -e "${GREEN}=== Installation Complete! ===${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Edit configuration:"
echo "   ${GREEN}nano /etc/whm2bunny/config.yaml${NC}"
echo ""
echo "2. Set environment variables in /etc/whm2bunny/env or export them:"
echo "   ${GREEN}export BUNNY_API_KEY='your-api-key'${NC}"
echo "   ${GREEN}export REVERSE_PROXY_IP='your-server-ip'${NC}"
echo ""
echo "3. Validate configuration:"
echo "   ${GREEN}/opt/whm2bunny/whm2bunny config validate /etc/whm2bunny/config.yaml${NC}"
echo ""
echo "4. Start the service:"
echo "   ${GREEN}systemctl start whm2bunny${NC}"
echo ""
echo "5. Check service status:"
echo "   ${GREEN}systemctl status whm2bunny${NC}"
echo ""
echo "6. View logs:"
echo "   ${GREEN}journalctl -u whm2bunny -f${NC}"
echo ""
echo "7. Register cPanel hooks (optional - for automatic hook registration):"
echo "   ${GREEN}/usr/local/cpanel/bin/manage_hooks add module Whm2bunnyHook${NC}"
echo ""
echo -e "${YELLOW}Webhook secret for cPanel hooks:${NC} $WHM2BUNNY_SECRET"
echo ""
